### ISSUE TITLE
Workflow for linking external datasets

### ISSUE THREAD

**Issue by mgns** [dbpedia/GSoC#5]
# Description
DBpedia is long time known as a central hub in the Linked Open Data (LOD) cloud as there are numerous datasets linked by DBpedia and even more linking to DBpedia resources. Nevertheless, outgoing links are highly appreciated. In the [DBpedia Links repository](https://github.com/dbpedia/links) people can upload there linksets or scripts to generate such. What is currently missing is a toolset to create links between DBpedia and external datasets automatically and to review them if needed. State-of-the-art tools for link creation between datasets are [SILK](https://github.com/silk-framework/silk) and [LIMES](https://github.com/dice-group/LIMES).
The student should create a workflow for automatic link generating and curation of automatically generated links, given there is a new dataset that should be linked to DBpedia. This workflow should be supported by a web-based GUI.

There are two levels of linking:
1. schema level: linking external vocabularies to the DBpedia ontology
2. instance level: linking resources from external datasets to DBpedia resources
Both levels can be considered in this project.
# Goals

# Impact
Get better links from DBpedia to external datasets.
# Warm up tasks
# Mentors
# Keywords
data quality, linking

**Comment by icemc** [comment]
Hello @mgns discovered there is no mentor assigned to this project, though I've started working on a proposal for GSOC. Can I continue writing a proposal for it, since I;m interested in the project as a whole? What is the priority of this project(low, medium, high) as far as GSOC is concerned if I may ask? I discovered it doesn't have any warmup task like the other projects, I't would be great if it had one, so that students can get busy with the warmup task and by the time they are done they would have had improve their knowledge of the DBpedia project as a whole. Cheers

**Comment by mgns** [comment]
Hello @icemc, yes a proposal for this project is highly welcome.

**Comment by Gautamshahi** [comment]
@mgns I have experience of working with SILk, Do you want to build a linking interface or create link data by using the existing interface like SILK?

looking forward to having a discussion.

**Comment by mgns** [comment]
SILK is one option for creating links between datasets. Using SILK has some problems: one is the configuration, which needs some expert knowledge; another one that both datasets need to be loaded to a SPARQL endpoint; furthermore there might be non-RDF datasets, such as a JSON or CSV of names and identifiers from a authority dataset (such as https://dictionaryofsydney.org/browse/person).
Question would be, how this can be eased for ad-hoc linking between DBpedia and a third party dataset. A web interface would be a great help.
