### ISSUE TITLE
Mapping Generation from Resource Descriptions

### ISSUE THREAD

**Issue by mgns** [dbpedia/GSoC#7]
# Description
DBpedia currently maintains mappings between Wikipedia infobox template properties to the DBpedia ontology, since several similar templates exist (in single as well as over multiple languages) to describe closely related types of infoboxes. The aim of the project is to enrich and possibly correct the existing mappings with a data-driven method to propose or generate mappings automatically by analyzing instance data from distinct language-specific datasets. This will be a follow-up of a [previous GSoC project](https://summerofcode.withgoogle.com/archive/2016/projects/5465189923160064/), which mainly mapped the classes to infobox templates.
A central goal is also to map Wikidata property identifiers.
# Goals
Provide suggestions (eg by using statistical probabilities) for template parameters which properties from DBpedia ontology and from Wikidata should be mapped.
# Impact
Increase the coverage for mapped languages and yet not mapped languages, which finally leads to better data quality.
# Warm up tasks
Familiarize with and evaluate the results of the [previous project code base](https://github.com/dbpedia/mappings-autogeneration) (no fixed stipulation to re-use this).
# Mentors

# Keywords
mappings, knowledge base completion, data quality

**Comment by apoorvjain25** [comment]
Hey! I am really interested in this project, can you please guide me that how should I proceed forward?

**Comment by sandrapraetor** [comment]
Hi, I am really sorry no one has contacted you, yet. As you were quite late to get in touch (3 days before the deadline) our mentors have been very busy helping all the other students that started their applications weeks ago. We love to mentor you next year, but keep in mind to get in touch with us as early as possible, so that our mentors can assist you in drafting a well structured and mature proposal that is the first step to a successful project. Thank you for your interest and I hope we see you next year.
